import { Role } from "@prisma/client";
import { requireActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { FormError, PageHeader } from "@/components/page-header";
import { createAuthorization, revokeAuthorization, saveEnterpriseProduct, saveEnterpriseSeries, syncEnterpriseCatalog } from "../../phase-one-actions";

export default async function EnterpriseProducts({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const actor = await requireActor([Role.ENTERPRISE_ADMIN]); const query = await searchParams; const enterpriseId=actor.enterpriseId!;
  const [series, stores, authorizations] = await Promise.all([db.enterpriseSeries.findMany({ where: { enterpriseId }, include: { products: { include: { variants: true } } }, orderBy: { createdAt: "desc" } }), db.store.findMany({ where: { isActive: true, authorizationEnabled: true }, orderBy: { name: "asc" } }), db.productAuthorization.findMany({ where: { enterpriseId }, include: { store: true, series: true }, orderBy: { createdAt: "desc" } })]);
  return <><PageHeader title="产品系列与商品授权" description="企业维护内容字段；店铺独立维护价格、库存、分类、排序和上下架" actions={<form action={syncEnterpriseCatalog}><button className="btn btn-primary">同步到已授权店铺</button></form>} /><FormError message={query.error} />
    <div className="grid gap-5 xl:grid-cols-2"><section className="panel p-5"><h2 className="font-bold">新建系列</h2><form action={saveEnterpriseSeries} className="mt-4 flex gap-3"><input className="field" name="name" required /><button className="btn btn-primary">新增</button></form></section><section className="panel p-5"><h2 className="font-bold">发起系列授权</h2><form action={createAuthorization} className="mt-4 flex gap-3"><select className="field" name="seriesId" required><option value="">选择系列</option>{series.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" name="storeId" required><option value="">选择店铺</option>{stores.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn btn-primary">发起</button></form></section></div>
    <details className="panel my-5"><summary className="cursor-pointer px-5 py-4 font-bold">新增企业产品和默认规格</summary><form action={saveEnterpriseProduct} className="form-grid border-t p-5"><label className="label">系列<select className="field" name="seriesId" required>{series.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="label">产品名称<input className="field" name="name" required /></label><label className="label">产品编码<input className="field" name="code" required /></label><label className="label">主图 URL<input className="field" name="mainImageUrl" type="url" required /></label><label className="label">单位<input className="field" name="unit" defaultValue="件" required /></label><label className="label">建议价<input className="field" name="suggestedPrice" type="number" min="0" /></label><label className="label">规格名称<input className="field" name="variantName" defaultValue="默认规格" required /></label><label className="label">规格编码<input className="field" name="variantCode" required /></label><label className="label col-span-full">详情<textarea className="field" name="description" /></label><button className="btn btn-primary">保存产品</button></form></details>
    <section className="panel table-wrap mb-5"><table><thead><tr><th>系列</th><th>产品</th><th>规格</th></tr></thead><tbody>{series.flatMap((s)=>s.products.map((p)=><tr key={p.id}><td>{s.name}</td><td><strong>{p.name}</strong><div className="muted text-xs">{p.code}</div></td><td>{p.variants.map(v=>`${v.name} (${v.code})`).join("、")}</td></tr>))}</tbody></table></section>
    <section className="panel table-wrap"><table><thead><tr><th>系列</th><th>目标店铺</th><th>状态</th><th>操作</th></tr></thead><tbody>{authorizations.map((item)=><tr key={item.id}><td>{item.series.name}</td><td>{item.store.name}</td><td>{item.status}</td><td>{item.status === "ACTIVE" && <form action={revokeAuthorization}><input type="hidden" name="id" value={item.id}/><button className="btn min-h-8 text-xs">撤销并下架</button></form>}</td></tr>)}</tbody></table></section>
  </>;
}
