"use client";

import Link from "next/link";
import { Heart, MessageCircle, Phone, ShoppingBag } from "lucide-react";
import { useEffect, useState } from "react";
import { usePublicCart } from "@/components/public/cart-provider";
import type { PublicProduct } from "@/lib/public-catalog";
import { customerHref, storeHref } from "@/lib/public-links";

export function ProductDetail({ product, store, refCode, favorite, customerActive }: { product: PublicProduct; store: { slug: string; phone: string }; refCode?: string; favorite: boolean; customerActive: boolean }) {
  const [variantId, setVariantId] = useState(product.variants[0]?.id ?? null); const variant = product.variants.find((item) => item.id === variantId); const images = [variant?.imageUrl || product.mainImageUrl, product.mainImageUrl, ...product.galleryImageUrls.split(/\r?\n/)].filter((value, index, values): value is string => Boolean(value) && values.indexOf(value) === index); const [image, setImage] = useState(images[0]); const { add } = usePublicCart();
  useEffect(() => { const sessionId = sessionStorage.getItem("yc-session") || crypto.randomUUID(); sessionStorage.setItem("yc-session", sessionId); void fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeSlug: store.slug, sessionId, eventId: crypto.randomUUID(), type: "PRODUCT_VIEW", productId: product.id, ref: refCode || null }) }); }, [product.id, refCode, store.slug]);
  async function toggleFavorite() { if (!customerActive) { location.href = customerHref(store.slug, refCode, location.pathname + location.search); return; } await fetch("/api/favorites", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeSlug: store.slug, productId: product.id }) }); location.reload(); }
  function addToCart() { add(product.id, variantId); const sessionId = sessionStorage.getItem("yc-session") || crypto.randomUUID(); sessionStorage.setItem("yc-session", sessionId); void fetch("/api/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeSlug: store.slug, sessionId, eventId: crypto.randomUUID(), type: "CART_ADD", productId: product.id, ref: refCode || null }) }); }
  return <main className="public-detail"><section className="public-gallery"><img src={image} alt={product.name}/><nav>{images.map((url) => <button className={image === url ? "active" : ""} onClick={() => setImage(url)} key={url}><img src={url} alt=""/></button>)}</nav></section><section className="public-detail-info"><small>{product.category?.name || "云丞精选"} · {product.code}</small><div className="flex items-start justify-between gap-3"><h1>{product.name}</h1><button aria-label="收藏" onClick={() => void toggleFavorite()}><Heart fill={favorite ? "currentColor" : "none"}/></button></div><strong>{variant?.price || product.price ? `¥${Number(variant?.price || product.price).toLocaleString()}` : "价格面议"}</strong><p>{product.description || "精心挑选的家居单品，为空间带来舒适与质感。"}</p>{product.variants.length > 0 && <div className="public-variants"><h2>选择规格</h2>{product.variants.map((item) => <button className={variantId === item.id ? "active" : ""} onClick={() => { setVariantId(item.id); setImage(item.imageUrl || product.mainImageUrl); }} key={item.id}>{item.name}{item.specification ? ` · ${item.specification}` : ""}</button>)}</div>}</section>{product.detailImageUrls.split(/\r?\n/).filter(Boolean).length > 0 && <section className="public-detail-images"><h2>商品详情</h2>{product.detailImageUrls.split(/\r?\n/).filter(Boolean).map((url) => <img src={url} alt="" key={url}/>)}</section>}<footer className="public-buybar"><a href={`tel:${store.phone}`}><Phone size={18}/><small>联系</small></a><button onClick={() => void toggleFavorite()}><Heart size={18}/><small>收藏</small></button><button className="primary" onClick={addToCart}><ShoppingBag size={18}/>加入开单</button><Link href={storeHref(store.slug, "cart", refCode)}><MessageCircle size={18}/>去开单</Link></footer></main>;
}
