"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import type { PageComponentV2, PageConfigV2 } from "@/lib/page-config";
import { Storefront, type StorefrontEmployee, type StorefrontProduct, type StorefrontStore } from "@/app/s/[slug]/storefront";
import { publishPage, savePageDraft } from "../../phase-one-actions";

const labels:Record<PageComponentV2["type"],string>={storeHeader:"店铺头部",employeeCard:"员工名片",image:"图片广告",text:"标题 / 正文",richText:"富文本",productSearch:"商品搜索",categoryNav:"分类导航",productGrid:"商品网格",contentCard:"内容卡片",video:"视频",divider:"分隔线"};
const types=Object.keys(labels) as PageComponentV2["type"][];
type Category={id:string;name:string};
type Props={page:{id:string;title:string;slug:string;config:PageConfigV2;published:boolean;isHome:boolean};publicUrl:string;store:StorefrontStore;employee:StorefrontEmployee;products:StorefrontProduct[];categories:Category[]};

function makeComponent(type:PageComponentV2["type"],products:StorefrontProduct[],categories:Category[]):PageComponentV2{
  const id=crypto.randomUUID();
  switch(type){
    case "storeHeader":return{id,type,style:"compact",subtitle:"家居美学 · 意向开单"};case "employeeCard":return{id,type,style:"dark"};case "image":return{id,type,url:products[0]?.mainImageUrl??"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200",alt:"图片广告"};case "text":return{id,type,title:"品牌标题",body:"介绍您的空间与服务"};case "richText":return{id,type,html:"<p>富文本内容</p>"};case "productSearch":return{id,type,placeholder:"搜索商品"};case "categoryNav":return{id,type,title:"商品分类"};case "productGrid":return{id,type,title:"精选商品",source:categories[0]?{mode:"all"}:{mode:"all"}};case "contentCard":return{id,type,title:"设计灵感",body:"用材质与光线塑造理想之家"};case "video":return{id,type,url:"https://www.w3schools.com/html/mov_bbb.mp4"};case "divider":return{id,type};
  }
}

export function PageEditor({page,publicUrl,store,employee,products,categories}:Props){
  const [components,setComponents]=useState(page.config.components);const [selectedId,setSelectedId]=useState(page.config.components[0]?.id??"");const [dragged,setDragged]=useState<string|null>(null);
  const selected=components.find(item=>item.id===selectedId);const config=useMemo(()=>JSON.stringify({version:2,components}),[components]);
  const update=(patch:Partial<PageComponentV2>)=>setComponents(items=>items.map(item=>item.id===selectedId?{...item,...patch} as PageComponentV2:item));
  function add(type:PageComponentV2["type"]){const component=makeComponent(type,products,categories);setComponents(items=>[...items,component]);setSelectedId(component.id)}
  function move(id:string,by:number){setComponents(items=>{const index=items.findIndex(item=>item.id===id),next=index+by;if(index<0||next<0||next>=items.length)return items;const copy=[...items];[copy[index],copy[next]]=[copy[next],copy[index]];return copy})}
  function drop(targetId:string){if(!dragged||dragged===targetId)return;setComponents(items=>{const from=items.findIndex(x=>x.id===dragged),to=items.findIndex(x=>x.id===targetId);const copy=[...items];const [item]=copy.splice(from,1);copy.splice(to,0,item);return copy});setDragged(null)}
  function remove(id:string){setComponents(items=>items.filter(item=>item.id!==id));if(selectedId===id)setSelectedId("")}
  const textField=(label:string,value:string,onChange:(value:string)=>void,multiline=false)=><label className="label">{label}{multiline?<textarea className="field min-h-24" value={value} onChange={e=>onChange(e.target.value)}/>:<input className="field" value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
  function Properties(){if(!selected)return <div className="empty">选择画布中的组件后配置</div>;
    const selectedProductIds=selected.type==="productGrid"&&selected.source.mode==="selected"?selected.source.productIds:[];
    return <div className="grid gap-4"><div><span className="badge">{labels[selected.type]}</span><p className="muted mt-2 text-xs">组件身份数据由当前店铺与分享员工动态绑定。</p></div>
      {selected.type==="storeHeader"&&<>{textField("副标题",selected.subtitle,value=>update({subtitle:value}))}<label className="label">样式<select className="field" value={selected.style} onChange={e=>update({style:e.target.value as "compact"|"hero"})}><option value="compact">紧凑</option><option value="hero">品牌展示</option></select></label></>}
      {selected.type==="employeeCard"&&<label className="label">样式<select className="field" value={selected.style} onChange={e=>update({style:e.target.value as "dark"|"light"})}><option value="dark">深色</option><option value="light">浅色</option></select></label>}
      {selected.type==="text"&&<>{textField("标题",selected.title,value=>update({title:value}))}{textField("正文",selected.body,value=>update({body:value}),true)}</>}
      {selected.type==="richText"&&textField("安全富文本（HTML）",selected.html,value=>update({html:value}),true)}
      {selected.type==="image"&&<><label className="label">选择店铺素材<select className="field" value="" onChange={e=>e.target.value&&update({url:e.target.value})}><option value="">选择 Logo 或商品图片</option>{store.logoUrl&&<option value={store.logoUrl}>店铺 Logo</option>}{products.map(product=><option key={product.id} value={product.mainImageUrl}>{product.name}</option>)}</select></label>{textField("图片 HTTP(S) 地址",selected.url,value=>update({url:value}))}{textField("替代文字",selected.alt,value=>update({alt:value}))}{textField("点击链接（可空）",selected.link??"",value=>update({link:value||undefined}))}</>}
      {selected.type==="productSearch"&&textField("提示文字",selected.placeholder,value=>update({placeholder:value}))}
      {selected.type==="categoryNav"&&textField("标题",selected.title,value=>update({title:value}))}
      {selected.type==="productGrid"&&<>{textField("标题",selected.title,value=>update({title:value}))}<label className="label">商品来源<select className="field" value={selected.source.mode} onChange={e=>{const mode=e.target.value;if(mode==="all")update({source:{mode}});if(mode==="category")update({source:{mode,categoryId:categories[0]?.id??""}});if(mode==="selected")update({source:{mode,productIds:[]}})}}><option value="all">全部商品</option><option value="category">指定分类</option><option value="selected">指定商品</option></select></label>{selected.source.mode==="category"&&<label className="label">分类<select className="field" value={selected.source.categoryId} onChange={e=>update({source:{mode:"category",categoryId:e.target.value}})}>{categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label>}{selected.source.mode==="selected"&&<fieldset className="grid gap-2"><legend className="mb-2 text-sm font-semibold">选择商品</legend>{products.map(product=><label className="flex items-center gap-2 text-sm" key={product.id}><input type="checkbox" checked={selectedProductIds.includes(product.id)} onChange={e=>update({source:{mode:"selected",productIds:e.target.checked?[...selectedProductIds,product.id]:selectedProductIds.filter(id=>id!==product.id)}})}/>{product.name}</label>)}</fieldset>}</>}
      {selected.type==="contentCard"&&<>{textField("标题",selected.title,value=>update({title:value}))}{textField("正文",selected.body,value=>update({body:value}),true)}{textField("图片地址（可空）",selected.imageUrl??"",value=>update({imageUrl:value||undefined}))}</>}
      {selected.type==="video"&&<>{textField("视频地址",selected.url,value=>update({url:value}))}{textField("封面地址（可空）",selected.poster??"",value=>update({poster:value||undefined}))}</>}
      {selected.type==="divider"&&<p className="muted text-sm">分隔线无需额外配置。</p>}
    </div>}
  return <><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link className="muted text-sm" href="/admin/pages">← 页面列表</Link><h1 className="page-title mt-2">装修：{page.title}</h1><p className="muted mt-1 text-sm">{page.published?page.isHome?"已发布 · 当前主页":"已发布":"草稿"}</p></div><div className="actions"><form action={savePageDraft}><input type="hidden" name="id" value={page.id}/><input type="hidden" name="config" value={config}/><button className="btn">保存草稿</button></form><form action={publishPage}><input type="hidden" name="id" value={page.id}/><input type="hidden" name="config" value={config}/><input type="hidden" name="makeHome" value="false"/><button className="btn btn-primary">发布当前版本</button></form>{!page.isHome&&<form action={publishPage}><input type="hidden" name="id" value={page.id}/><input type="hidden" name="config" value={config}/><input type="hidden" name="makeHome" value="true"/><button className="btn">发布并设主页</button></form>}{page.published&&<a className="btn" target="_blank" href={publicUrl}>查看线上页</a>}</div></div>
    <div className="grid gap-5 xl:grid-cols-[210px_minmax(300px,1fr)_340px]"><aside className="panel p-4"><h2 className="mb-3 font-bold">组件</h2><div className="grid gap-2">{types.map(type=><button type="button" key={type} className="btn justify-start text-sm" onClick={()=>add(type)}>＋ {labels[type]}</button>)}</div></aside>
      <section className="grid content-start gap-3"><div className="mb-1 flex items-center justify-between"><h2 className="font-bold">页面结构</h2><span className="muted text-xs">拖动或使用箭头排序</span></div>{components.map((item,index)=><button type="button" draggable onDragStart={()=>setDragged(item.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(item.id)} onClick={()=>setSelectedId(item.id)} className={`panel cursor-move p-4 text-left ${selectedId===item.id?"ring-2 ring-[#176b45]":""}`} key={item.id}><div className="flex items-center justify-between gap-2"><div><span className="muted mr-2 text-xs">{index+1}</span><strong>{labels[item.type]}</strong></div><div className="actions"><span role="button" className="btn min-h-7 px-2 text-xs" onClick={e=>{e.stopPropagation();move(item.id,-1)}}>↑</span><span role="button" className="btn min-h-7 px-2 text-xs" onClick={e=>{e.stopPropagation();move(item.id,1)}}>↓</span><span role="button" className="btn btn-danger min-h-7 px-2 text-xs" onClick={e=>{e.stopPropagation();remove(item.id)}}>删除</span></div></div></button>)}{!components.length&&<div className="empty panel">从左侧添加组件</div>}</section>
      <aside className="grid content-start gap-5"><div className="panel p-4"><h2 className="mb-4 font-bold">属性</h2><Properties/></div><div className="sticky top-5 overflow-hidden rounded-[28px] border-[7px] border-[#252525] bg-[#f8f6f2] shadow-xl"><div className="bg-[#252525] py-2 text-center text-xs text-white">真实移动端预览 · 不写入数据</div><div className="relative h-[650px] overflow-y-auto"><Storefront store={store} categories={categories} products={products} employee={employee} pageConfig={{version:2,components}} pageSlug={page.slug} customerActive={false} favoriteIds={[]} preview/></div></div></aside></div>
  </>;
}
