"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Check, Copy, Heart, Minus, Phone, Plus, Send, ShoppingBag, X } from "lucide-react";
import type { PageComponentV2, PageConfigV2 } from "@/lib/page-config";

export type StorefrontVariant={id:string;name:string;code:string;price:string|null};
export type StorefrontProduct={id:string;name:string;code:string;mainImageUrl:string;detailImageUrls:string;specification:string;price:string|null;unit:string;description:string;categoryId:string|null;variants:StorefrontVariant[]};
export type StorefrontEmployee={name:string;phone:string|null;wechat:string|null;title:string|null;bio:string|null;avatarUrl:string|null;shareCode:string|null}|null;
export type StorefrontStore={slug:string;name:string;logoUrl:string|null;phone:string;address:string};
type CartItem={product:StorefrontProduct;variant:StorefrontVariant|null;quantity:number;remark:string};
type Props={store:StorefrontStore;categories:{id:string;name:string}[];products:StorefrontProduct[];employee:StorefrontEmployee;pageConfig:PageConfigV2;pageSlug:string;customerActive:boolean;favoriteIds:string[];preview?:boolean};

function browserSessionId(){let id=sessionStorage.getItem("yc-session");if(!id){id=crypto.randomUUID();sessionStorage.setItem("yc-session",id)}return id}

export function Storefront({store,categories,products,employee,pageConfig,pageSlug,customerActive,favoriteIds,preview=false}:Props){
  const [category,setCategory]=useState("all");const [query,setQuery]=useState("");const [cart,setCart]=useState<Record<string,CartItem>>({});const [selected,setSelected]=useState<StorefrontProduct|null>(null);const [selectedVariant,setSelectedVariant]=useState("");const [showCart,setShowCart]=useState(false);const [submitted,setSubmitted]=useState<string|null>(null);const [favorites,setFavorites]=useState(new Set(favoriteIds));
  const components=pageConfig.components;const cartItems=Object.values(cart);const count=cartItems.reduce((n,x)=>n+x.quantity,0);const ref=employee?.shareCode??"";
  const recordEvent=useCallback(async(type:string,productId?:string)=>{if(preview)return;await fetch("/api/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeSlug:store.slug,sessionId:browserSessionId(),eventId:crypto.randomUUID(),type,productId,pageSlug,ref:ref||null})}).catch(()=>null)},[pageSlug,preview,ref,store.slug]);
  useEffect(()=>{void recordEvent("PAGE_VIEW")},[recordEvent]);
  function add(product:StorefrontProduct,variantId?:string){const variant=product.variants.find(x=>x.id===variantId)??product.variants[0]??null;const key=`${product.id}:${variant?.id??"default"}`;setCart(items=>({...items,[key]:items[key]?{...items[key],quantity:items[key].quantity+1}:{product,variant,quantity:1,remark:""}}));void recordEvent("CART_ADD",product.id)}
  function change(key:string,by:number){setCart(items=>{const next={...items};const quantity=(next[key]?.quantity??0)+by;if(quantity<=0)delete next[key];else next[key]={...next[key],quantity};return next})}
  async function favorite(productId:string){if(preview)return;if(!customerActive){location.href=`/customer?store=${store.slug}&ref=${ref}`;return}const response=await fetch("/api/favorites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeSlug:store.slug,productId})});if(response.ok){const result=await response.json();setFavorites(items=>{const next=new Set(items);if(result.favorite)next.add(productId);else next.delete(productId);return next});void recordEvent("FAVORITE",productId)}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(preview){setSubmitted("预览模式：未写入订单");return}if(!customerActive){location.href=`/customer?store=${store.slug}&ref=${ref}`;return}const data=new FormData(e.currentTarget);const response=await fetch("/api/public/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeSlug:store.slug,ref:ref||null,clientRequestId:crypto.randomUUID(),customerAddress:data.get("address"),customerRemark:data.get("remark"),items:cartItems.map(x=>({productId:x.product.id,variantId:x.variant?.id,quantity:x.quantity,remark:x.remark}))})});const result=await response.json();if(!response.ok){alert(result.error??"提交失败");return}setSubmitted(result.orderNo);setCart({})}
  const productsFor=(component:Extract<PageComponentV2,{type:"productGrid"}>)=>products.filter((product)=>{
    const source=component.source;const sourceMatch=source.mode==="all"||(source.mode==="category"&&product.categoryId===source.categoryId)||(source.mode==="selected"&&source.productIds.includes(product.id));
    return sourceMatch&&(category==="all"||product.categoryId===category)&&(!query||product.name.toLowerCase().includes(query.toLowerCase())||product.code.toLowerCase().includes(query.toLowerCase()));
  });
  function ProductGrid({component}:{component:Extract<PageComponentV2,{type:"productGrid"}>}){const visible=productsFor(component);return <section className="mb-4"><h2 className="mb-3 font-bold">{component.title}</h2>{visible.length?<div className="grid grid-cols-2 gap-3">{visible.map(product=><article key={product.id} className="overflow-hidden rounded-xl bg-white"><button className="relative block w-full" onClick={()=>{setSelected(product);setSelectedVariant(product.variants[0]?.id??"");void recordEvent("PRODUCT_VIEW",product.id)}}><img src={product.mainImageUrl} alt={product.name} className="aspect-square w-full object-cover"/></button><div className="p-3"><div className="flex justify-between gap-2"><strong className="truncate text-sm">{product.name}</strong><button disabled={preview} onClick={()=>void favorite(product.id)} aria-label="收藏"><Heart size={17} fill={favorites.has(product.id)?"currentColor":"none"}/></button></div><p className="muted mt-1 truncate text-xs">{product.variants[0]?.name??product.specification}</p><div className="mt-3 flex items-center justify-between"><strong className="text-[#a46c2a]">{product.price?`¥${Number(product.price).toLocaleString()}`:"面议"}</strong><button className="rounded bg-[#3f4f43] p-2 text-white" onClick={()=>add(product)}><Plus size={14}/></button></div></div></article>)}</div>:<div className="rounded-xl bg-white p-8 text-center text-sm text-[#777]">暂无可展示商品</div>}</section>}
  function Block({item}:{item:PageComponentV2}){
    if(item.type==="storeHeader")return <header className={`mb-4 bg-white ${item.style==="hero"?"rounded-xl p-6":"-mx-4 -mt-4 p-5"}`}><div className="flex items-center gap-3"><img src={store.logoUrl??products[0]?.mainImageUrl} alt="" className={`${item.style==="hero"?"size-14":"size-10"} rounded-full object-cover`}/><div><h1 className="font-bold">{store.name}</h1><p className="muted text-xs">{item.subtitle}</p></div>{!preview&&<Link className="btn ml-auto min-h-8 text-xs" href={customerActive?"/me":`/customer?store=${store.slug}&ref=${ref}`}>{customerActive?"我的":"登录/注册"}</Link>}</div></header>;
    if(item.type==="employeeCard")return <section className={`mb-4 rounded-xl p-4 ${item.style==="dark"?"bg-[#4a4a46] text-white":"bg-white"}`}><div className="flex items-center gap-3"><img src={employee?.avatarUrl??store.logoUrl??products[0]?.mainImageUrl} alt="" className="size-14 rounded-full object-cover"/><div className="min-w-0 flex-1"><p>{employee?.name??store.name}</p><strong>{employee?.title??"店铺顾问"}</strong><p className={`truncate text-xs ${item.style==="dark"?"text-white/70":"muted"}`}>{employee?.bio??store.address}</p></div><a className="rounded bg-white p-2 text-[#333]" href={preview?undefined:`tel:${employee?.phone??store.phone}`}><Phone size={16}/></a>{employee?.wechat&&<button className="rounded bg-white p-2 text-[#333]" onClick={()=>!preview&&navigator.clipboard.writeText(employee.wechat!)}><Copy size={16}/></button>}</div></section>;
    if(item.type==="image"){const picture=<img src={item.url} alt={item.alt} className="mb-4 w-full rounded-xl"/>;return item.link&&!preview?<a href={item.link} key={item.id}>{picture}</a>:picture}
    if(item.type==="text")return <section className="mb-4 rounded-xl bg-white p-4"><strong>{item.title}</strong><p className="muted mt-2 text-sm whitespace-pre-wrap">{item.body}</p></section>;
    if(item.type==="richText")return <div className="prose mb-4 rounded-xl bg-white p-4" dangerouslySetInnerHTML={{__html:item.html}}/>;
    if(item.type==="productSearch")return <input className="field mb-4" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={item.placeholder}/>;
    if(item.type==="categoryNav")return <section className="mb-4"><h2 className="mb-2 text-sm font-bold">{item.title}</h2><nav className="flex gap-2 overflow-x-auto"><button className={`rounded-full px-4 py-2 text-sm ${category==="all"?"bg-[#3f4f43] text-white":"bg-white"}`} onClick={()=>setCategory("all")}>全部</button>{categories.map(x=><button key={x.id} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${category===x.id?"bg-[#3f4f43] text-white":"bg-white"}`} onClick={()=>setCategory(x.id)}>{x.name}</button>)}</nav></section>;
    if(item.type==="productGrid")return <ProductGrid component={item}/>;
    if(item.type==="contentCard")return <section className="mb-4 overflow-hidden rounded-xl bg-white">{item.imageUrl&&<img src={item.imageUrl} alt="" className="aspect-[2/1] w-full object-cover"/>}<div className="p-4"><strong>{item.title}</strong><p className="muted mt-2 text-sm whitespace-pre-wrap">{item.body}</p></div></section>;
    if(item.type==="video")return <video controls poster={item.poster} className="mb-4 w-full rounded-xl" src={item.url}/>;
    return <hr className="my-5"/>;
  }
  return <main className={`${preview?"relative":"min-h-screen"} bg-[#f7f6f2] pb-24 text-[#302b26]`}><section className="mx-auto max-w-[520px] px-4 pt-4">{components.map(item=><Block key={item.id} item={item}/>)}</section>
    <div className={`${preview?"sticky":"fixed"} inset-x-0 bottom-0 z-20 mx-auto max-w-[520px] bg-white p-3`}><button className="flex w-full justify-between rounded-xl bg-[#3f4f43] p-3 text-white" onClick={()=>setShowCart(true)}><span><ShoppingBag className="mr-2 inline" size={18}/>已选 {count} 件</span><span>进入开单 ›</span></button></div>
    {selected&&<div className="absolute inset-0 z-30 grid items-end bg-black/40" onClick={()=>setSelected(null)}><div className="mx-auto w-full max-w-[520px] rounded-t-2xl bg-white p-5" onClick={e=>e.stopPropagation()}><button className="float-right" onClick={()=>setSelected(null)}><X/></button><img src={selected.mainImageUrl} alt="" className="aspect-[1.8] w-full rounded-xl object-cover"/><h2 className="mt-4 text-xl font-bold">{selected.name}</h2>{selected.variants.length>0&&<select className="field mt-3" value={selectedVariant} onChange={e=>setSelectedVariant(e.target.value)}>{selected.variants.map(v=><option key={v.id} value={v.id}>{v.name} · {v.price?`¥${v.price}`:"面议"}</option>)}</select>}<p className="muted mt-3 text-sm">{selected.description}</p><button className="btn btn-primary mt-4" onClick={()=>{add(selected,selectedVariant);setSelected(null)}}><Plus size={16}/>选择规格并加入</button></div></div>}
    {showCart&&<div className="absolute inset-0 z-30 bg-black/40"><div className="absolute inset-x-0 bottom-0 mx-auto max-h-[88vh] max-w-[520px] overflow-y-auto rounded-t-2xl bg-[#fbfaf8] p-5"><button className="float-right" onClick={()=>setShowCart(false)}><X/></button><h2 className="text-xl font-bold">确认开单</h2>{submitted?<div className="mt-5 rounded-xl bg-[#e8f2eb] p-6 text-center"><Check className="mx-auto"/><strong className="mt-3 block">{preview?"预览完成":"提交成功"}</strong><p className="muted text-sm">{submitted}</p></div>:<><div className="mt-4 grid gap-3">{cartItems.map((item)=>{const key=`${item.product.id}:${item.variant?.id??"default"}`;return <div key={key} className="rounded-xl bg-white p-3"><div className="flex items-center gap-3"><img src={item.product.mainImageUrl} alt="" className="size-12 rounded object-cover"/><div className="flex-1"><strong className="text-sm">{item.product.name}</strong><p className="muted text-xs">{item.variant?.name??item.product.specification}</p></div><button onClick={()=>change(key,-1)}><Minus size={15}/></button><span>{item.quantity}</span><button onClick={()=>change(key,1)}><Plus size={15}/></button></div><input className="field mt-2" placeholder="项目备注（选填）" value={item.remark} onChange={e=>setCart(items=>({...items,[key]:{...items[key],remark:e.target.value}}))}/></div>})}</div><form className="mt-4 grid gap-3" onSubmit={submit}><input className="field" name="address" placeholder="联系地址（选填）"/><textarea className="field" name="remark" placeholder="整单备注（选填）"/><button className="btn btn-primary" disabled={!cartItems.length}><Send size={16}/>{preview?"模拟提交（不写入）":customerActive?"提交购买意向":"登录后提交"}</button></form></>}</div></div>}
  </main>;
}
