"use client";

import { useMemo, useState } from "react";
import { Check, Copy, Minus, Phone, Plus, Send, ShoppingBag, X } from "lucide-react";

type Category = { id: string; name: string };
type Product = { id: string; name: string; code: string; mainImageUrl: string; detailImageUrls: string; specification: string; price: string | null; unit: string; description: string; categoryId: string };
type Employee = { name: string; phone: string | null; wechat: string | null; title: string | null; bio: string | null; avatarUrl: string | null; shareCode: string | null } | null;

export function Storefront({ store, categories, products, employee }: { store: { slug: string; name: string; logoUrl: string | null; phone: string; address: string }; categories: Category[]; products: Product[]; employee: Employee }) {
  const [activeCategory, setActiveCategory] = useState(categories[0]?.id ?? "all");
  const [cart, setCart] = useState<Record<string, number>>({});
  const [selected, setSelected] = useState<Product | null>(null);
  const [showCart, setShowCart] = useState(false);
  const [submitted, setSubmitted] = useState<{ orderNo: string; phone: string } | null>(null);
  const visible = useMemo(() => activeCategory === "all" ? products : products.filter((item) => item.categoryId === activeCategory), [activeCategory, products]);
  const cartItems = products.filter((item) => cart[item.id]).map((item) => ({ product: item, quantity: cart[item.id] }));
  const count = cartItems.reduce((sum, item) => sum + item.quantity, 0);
  function add(id: string) { setCart((current) => ({ ...current, [id]: (current[id] ?? 0) + 1 })); }
  function change(id: string, amount: number) { setCart((current) => { const next = Math.max(0, (current[id] ?? 0) + amount); const copy = { ...current }; if (!next) delete copy[id]; else copy[id] = next; return copy; }); }
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const response = await fetch("/api/public/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeSlug: store.slug, ref: employee?.shareCode ?? null, clientRequestId: crypto.randomUUID(), customerName: form.get("customerName"), customerPhone: form.get("customerPhone"), customerAddress: form.get("customerAddress"), customerRemark: form.get("customerRemark"), items: cartItems.map((item) => ({ productId: item.product.id, quantity: item.quantity })) }) });
    const result = await response.json(); if (!response.ok) { alert(result.error ?? "提交失败"); return; } setSubmitted({ orderNo: result.orderNo, phone: result.storePhone }); setCart({});
  }
  return <main className="min-h-screen bg-[#f7f6f2] pb-24 text-[#302b26]">
    <header className="mx-auto max-w-[520px] bg-white px-5 pb-4 pt-5"><div className="flex items-center gap-3"><img src={store.logoUrl ?? products[0]?.mainImageUrl} alt="" className="size-10 rounded-full object-cover" /><div><h1 className="text-lg font-bold">{store.name}</h1><p className="text-xs text-[#8d8177]">家居美学 · 一站式开单</p></div><a className="ml-auto grid size-9 place-items-center rounded-full bg-[#f1eee8]" href={`tel:${store.phone}`} aria-label="拨打店铺电话"><Phone size={17} /></a></div><div className="mt-4 flex items-center gap-2 rounded-full bg-[#f5f3ef] px-4 py-2.5 text-sm text-[#857970]"><span>⌕</span><span>搜索产品、系列、型号</span></div></header>
    <section className="mx-auto max-w-[520px] px-4 pt-3"><div className="relative h-48 overflow-hidden rounded-xl bg-[#d8cec3]"><img src={products[0]?.mainImageUrl} alt="店铺精选" className="h-full w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/60 to-transparent p-5 text-white"><p className="text-xs tracking-[.2em] text-white/80">GOOD LIVING</p><strong className="mt-1 block text-2xl">把家的质感，交给良材</strong></div></div></section>
    <section className="mx-auto max-w-[520px] px-4 pt-4"><div className="rounded-xl bg-[#4a4a46] p-4 text-white shadow-sm"><div className="flex items-center gap-3"><img src={employee?.avatarUrl ?? store.logoUrl ?? products[0]?.mainImageUrl} alt="" className="size-14 rounded-full border-2 border-white/30 object-cover" /><div className="min-w-0 flex-1"><p className="text-sm text-white/70">{employee?.name ?? "云丞顾问"}</p><strong className="mt-1 block truncate text-lg">{employee?.title ?? "良丞家居主理人"}</strong><p className="mt-1 truncate text-xs text-white/70">{employee?.bio ?? "从原木定制到全屋家具，一站式整装"}</p></div><div className="grid gap-2"><a className="flex items-center gap-1 rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#3c3a35]" href={`tel:${employee?.phone ?? store.phone}`}><Phone size={14} />电话</a>{employee?.wechat && <button className="flex items-center gap-1 rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#3c3a35]" onClick={() => navigator.clipboard.writeText(employee.wechat!)}><Copy size={14} />微信</button>}</div></div></div></section>
    <nav className="mx-auto flex max-w-[520px] gap-2 overflow-x-auto px-4 py-5"><button className={`rounded-full px-4 py-2 text-sm font-bold ${activeCategory === "all" ? "bg-[#3f4f43] text-white" : "bg-white text-[#81776e]"}`} onClick={() => setActiveCategory("all")}>全部</button>{categories.map((category) => <button key={category.id} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${activeCategory === category.id ? "bg-[#3f4f43] text-white" : "bg-white text-[#81776e]"}`} onClick={() => setActiveCategory(category.id)}>{category.name}</button>)}</nav>
    <section className="mx-auto max-w-[520px] px-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs tracking-[.15em] text-[#9b8b7e]">CURATED PRODUCTS</p><h2 className="mt-1 text-xl font-bold">精选好物</h2></div><span className="text-xs text-[#9b8b7e]">{visible.length} 件商品</span></div><div className="grid grid-cols-2 gap-3">{visible.map((product) => <article key={product.id} className="overflow-hidden rounded-xl bg-white shadow-[0_3px_15px_rgba(71,56,43,.06)]"><button className="block w-full text-left" onClick={() => setSelected(product)}><img src={product.mainImageUrl} alt={product.name} className="aspect-square w-full object-cover" /><div className="p-3"><p className="truncate text-sm font-bold">{product.name}</p><p className="mt-1 truncate text-xs text-[#978d84]">{product.specification}</p><div className="mt-3 flex items-center justify-between"><strong className="text-[#a46c2a]">{product.price ? `¥${Number(product.price).toLocaleString()}` : "面议"}</strong><span className="text-xs text-[#9b8b7e]">/{product.unit}</span></div></div></button><button className="mx-3 mb-3 flex w-[calc(100%-24px)] items-center justify-center gap-1 rounded-lg bg-[#3f4f43] py-2 text-xs font-bold text-white" onClick={() => add(product.id)}><Plus size={14} />加入开单</button></article>)}</div></section>
    <div className="fixed inset-x-0 bottom-0 z-20 mx-auto max-w-[520px] border-t border-[#e6e0d8] bg-white/95 p-3 backdrop-blur"><button className="flex w-full items-center justify-between rounded-xl bg-[#3f4f43] px-4 py-3 text-white" onClick={() => setShowCart(true)}><span className="flex items-center gap-2 text-sm font-bold"><ShoppingBag size={18} />已选 {count} 件</span><span className="flex items-center gap-1 text-sm">进入开单 <span>›</span></span></button></div>
    {selected && <div className="fixed inset-0 z-30 grid items-end bg-black/35 p-0 sm:place-items-center sm:p-4" onClick={() => setSelected(null)}><div className="max-h-[88vh] w-full max-w-[520px] overflow-y-auto rounded-t-2xl bg-white sm:rounded-2xl" onClick={(event) => event.stopPropagation()}><div className="relative"><img src={selected.mainImageUrl} alt={selected.name} className="aspect-[1.4] w-full object-cover" /><button className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90" onClick={() => setSelected(null)}><X size={18} /></button></div><div className="p-5"><h2 className="text-xl font-bold">{selected.name}</h2><p className="mt-2 text-sm text-[#83766b]">{selected.specification} · {selected.unit}</p><p className="mt-4 text-sm leading-6 text-[#625950]">{selected.description || "暂无商品描述"}</p><div className="mt-5 flex items-center justify-between"><strong className="text-xl text-[#a46c2a]">{selected.price ? `¥${Number(selected.price).toLocaleString()}` : "面议"}</strong><button className="btn btn-primary" onClick={() => { add(selected.id); setSelected(null); }}><Plus size={16} />加入开单</button></div></div></div></div>}
    {showCart && <div className="fixed inset-0 z-30 bg-black/35" onClick={() => setShowCart(false)}><div className="absolute inset-x-0 bottom-0 mx-auto max-h-[88vh] max-w-[520px] overflow-y-auto rounded-t-2xl bg-[#fbfaf8] p-5" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">确认开单</h2><button onClick={() => setShowCart(false)}><X /></button></div>{submitted ? <div className="rounded-xl bg-[#e8f2eb] p-6 text-center"><div className="mx-auto grid size-12 place-items-center rounded-full bg-[#3f8b61] text-white"><Check /></div><h3 className="mt-4 text-lg font-bold">开单提交成功</h3><p className="mt-2 text-sm text-[#587060]">订单编号：{submitted.orderNo}</p><p className="mt-1 text-xs text-[#71847a]">商家会尽快与您联系，联系电话 {submitted.phone}</p><button className="btn mt-5" onClick={() => { setSubmitted(null); setShowCart(false); }}>继续浏览</button></div> : <><div className="grid gap-3">{cartItems.map(({ product, quantity }) => <div key={product.id} className="flex items-center gap-3 rounded-xl bg-white p-3"><img src={product.mainImageUrl} alt="" className="size-14 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{product.name}</p><p className="text-xs text-[#9a8e84]">{product.specification}</p></div><div className="flex items-center gap-2"><button className="grid size-7 place-items-center rounded-full bg-[#f0eee9]" onClick={() => change(product.id, -1)}><Minus size={14} /></button><span className="w-5 text-center text-sm">{quantity}</span><button className="grid size-7 place-items-center rounded-full bg-[#f0eee9]" onClick={() => change(product.id, 1)}><Plus size={14} /></button></div></div>)}</div><p className="my-4 rounded-lg bg-[#f1ede6] p-3 text-xs leading-5 text-[#776e65]">本平台仅提交购买意向，不进行在线支付，最终价格和成交信息由商家确认。</p><form onSubmit={submit} className="grid gap-3"><input className="field" name="customerName" placeholder="您的姓名" required /><input className="field" name="customerPhone" placeholder="手机号" inputMode="tel" pattern="1[0-9]{10}" required /><input className="field" name="customerAddress" placeholder="联系地址（选填）" /><textarea className="field min-h-20" name="customerRemark" placeholder="备注（选填）" /><button className="btn btn-primary" disabled={!cartItems.length}><Send size={16} />提交购买意向</button></form></>}</div></div>}
  </main>;
}
