import { Role } from "@prisma/client";
import { ExternalLink } from "lucide-react";
import Link from "next/link";
import { requireActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { CopyLink } from "@/components/copy-link";
import { saveMyCard } from "../actions";

export default async function SharePage(){const actor=await requireActor([Role.STORE_ADMIN,Role.EMPLOYEE]);const employee=await db.user.findUnique({where:{id:actor.id},include:{store:true}});if(!employee?.store)return null;const path=employee.shareCode?`/s/${employee.store.slug}?ref=${employee.shareCode}`:null;return <><PageHeader title="我的分享与名片" description="有效管理员或员工来源优先展示；无效来源自动回退店铺默认名片" actions={path?<Link className="btn" href={path} target="_blank"><ExternalLink size={16}/>打开 H5</Link>:undefined}/><div className="grid gap-5 lg:grid-cols-2"><section className="panel p-6"><div className="flex items-center gap-4"><img src={employee.avatarUrl??employee.store.logoUrl??""} alt="" className="size-16 rounded-full object-cover"/><div><h2 className="font-bold">{employee.name}</h2><p className="muted text-sm">{employee.title??"店铺顾问"}</p></div></div>{path?<><code className="mt-5 block break-all rounded bg-[#f4f6f4] p-3 text-sm">{path}</code><CopyLink path={path}/></>:<p className="mt-5 rounded bg-[#fff4df] p-3 text-sm text-[#8a5b17]">保存名片后生成个人分享链接。</p>}</section><form action={saveMyCard} className="panel grid gap-3 p-6"><h2 className="font-bold">维护个人名片</h2>{!employee.wechat&&<p className="rounded bg-[#fff4df] p-3 text-sm text-[#8a5b17]">存量名片缺少微信号，请填写真实微信后保存。</p>}<input className="field" name="name" defaultValue={employee.name} placeholder="姓名" required/><input className="field" name="phone" defaultValue={employee.phone??""} placeholder="电话" required/><input className="field" name="wechat" defaultValue={employee.wechat??""} placeholder="真实微信号" required/><input className="field" name="title" defaultValue={employee.title??""} placeholder="职位"/><input className="field" name="bio" defaultValue={employee.bio??""} placeholder="名片文案"/><input className="field" name="avatarUrl" type="url" defaultValue={employee.avatarUrl??""} placeholder="头像 URL"/><button className="btn btn-primary">保存名片</button></form></div></>}
