"use client";

import Link from "next/link";
import { Check, Minus, Plus, Send, ShoppingBag } from "lucide-react";
import { useRef, useState } from "react";
import { usePublicCart } from "@/components/public/cart-provider";
import type { PublicCatalog } from "@/lib/public-catalog";
import { customerHref, storeHref } from "@/lib/public-links";

export function PublicCartPage({ catalog, refCode }: { catalog: PublicCatalog; refCode?: string }) {
  const { cart, ready, change, remark, clear } = usePublicCart(); const [message, setMessage] = useState(""); const [submitting, setSubmitting] = useState(false);
  const requestId = useRef<string | null>(null);
  const lines = cart.lines.map((line) => { const product = catalog.products.find((item) => item.id === line.productId); const variant = product?.variants.find((item) => item.id === line.variantId); return { ...line, product, variant }; }); const valid = lines.filter((line) => line.product);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!catalog.customerActive) { location.href = customerHref(catalog.store.slug, refCode, location.pathname + location.search); return; } setSubmitting(true); requestId.current ??= crypto.randomUUID(); const form = new FormData(event.currentTarget); const response = await fetch("/api/public/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeSlug: catalog.store.slug, ref: refCode || null, clientRequestId: requestId.current, customerAddress: form.get("address"), customerRemark: form.get("remark"), items: valid.map((line) => ({ productId: line.productId, variantId: line.variantId, quantity: line.quantity, remark: line.remark })) }) }); const result = await response.json(); setSubmitting(false); if (!response.ok) { setMessage(result.error || "提交失败"); return; } clear(); setMessage(`提交成功 · ${result.orderNo}`); }
  if (!ready) return <main className="public-cart"><div className="public-empty">正在读取开单商品…</div></main>;
  if (message.startsWith("提交成功")) return <main className="public-cart public-success"><Check/><h1>意向单已提交</h1><p>{message}</p><p>顾问会尽快与你联系，本次提交不会在线扣款或扣减库存。</p><Link href={storeHref(catalog.store.slug, "", refCode)}>返回首页</Link></main>;
  return <main className="public-cart"><header className="public-page-head"><h1>确认开单</h1><p>本页面用于提交购买意向，不产生在线支付。</p></header>{lines.some((line) => !line.product) && <div className="public-warning">部分商品已下架，请删除后再提交。</div>}<section className="public-cart-lines">{lines.map((line) => <article key={`${line.productId}:${line.variantId}`}>{line.product ? <><img src={line.variant?.imageUrl || line.product.mainImageUrl} alt=""/><div><h2>{line.product.name}</h2><p>{line.variant?.name || line.product.specification}</p><strong>{line.variant?.price || line.product.price ? `¥${Number(line.variant?.price || line.product.price).toLocaleString()}` : "面议"}</strong></div><footer><button onClick={() => change(line.productId, line.variantId, -1)}><Minus size={15}/></button><span>{line.quantity}</span><button onClick={() => change(line.productId, line.variantId, 1)}><Plus size={15}/></button></footer><input value={line.remark} onChange={(event) => remark(line.productId, line.variantId, event.target.value)} placeholder="商品备注（选填）"/></> : <><div><h2>商品已失效</h2></div><button onClick={() => change(line.productId, line.variantId, -line.quantity)}>删除</button></>}</article>)}</section>{!lines.length && <div className="public-empty"><ShoppingBag/><h2>还没有选择商品</h2><Link href={storeHref(catalog.store.slug, "category", refCode)}>去逛逛</Link></div>}{lines.length > 0 && <form className="public-order-form" onSubmit={submit}><input name="address" maxLength={200} placeholder="联系地址（选填）"/><textarea name="remark" maxLength={500} placeholder="整单备注（选填）"/><button disabled={submitting || valid.length !== lines.length}><Send size={17}/>{catalog.customerActive ? submitting ? "提交中…" : "提交购买意向" : "登录后提交"}</button>{message && <p>{message}</p>}</form>}</main>;
}
