"use client";

import Link from "next/link";
import { signOut } from "next-auth/react";
import { Camera, ChevronLeft, LockKeyhole, LogOut, QrCode, UserRound } from "lucide-react";
import { useState } from "react";

type StaffProfile = { username:string; roleLabel:string; storeName:string; storeSlug:string; shareCode:string; name:string; phone:string; wechat:string; title:string; bio:string; avatarUrl:string|null; wechatQrUrl:string|null };
export function StaffSettings({ initialProfile }: { initialProfile: StaffProfile }) {
  const [profile,setProfile]=useState(initialProfile); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const data=new FormData(event.currentTarget);const response=await fetch("/api/staff/settings/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),phone:data.get("phone"),wechat:data.get("wechat"),title:data.get("title"),bio:data.get("bio")})});const result=await response.json();if(response.ok)setProfile((current)=>({...current,...result.profile}));setMessage(response.ok?"名片已保存":result.error??"保存失败");setBusy(false)}
  async function password(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;const data=new FormData(form);const response=await fetch("/api/staff/settings/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:data.get("currentPassword"),newPassword:data.get("newPassword")})});const result=await response.json();setMessage(response.ok?"密码已更新":result.error??"修改失败");if(response.ok)form.reset();setBusy(false)}
  async function upload(type:"avatar"|"wechatQr",file:File|undefined){if(!file)return;setBusy(true);const body=new FormData();body.set("type",type);body.set("file",file);const response=await fetch("/api/staff/settings/assets",{method:"POST",body});const result=await response.json();const field=type==="avatar"?"avatarUrl":"wechatQrUrl";if(response.ok)setProfile((current)=>({...current,[field]:result.url}));setMessage(response.ok?(type==="avatar"?"头像已更新":"微信二维码已更新"):result.error??"上传失败");setBusy(false)}
  async function remove(type:"avatar"|"wechatQr"){setBusy(true);const response=await fetch("/api/staff/settings/assets",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({type})});const result=await response.json();const field=type==="avatar"?"avatarUrl":"wechatQrUrl";if(response.ok)setProfile((current)=>({...current,[field]:null}));setMessage(response.ok?(type==="avatar"?"头像已移除":"微信二维码已删除"):result.error??"移除失败");setBusy(false)}
  const sharePath=`/s/${profile.storeSlug}?ref=${encodeURIComponent(profile.shareCode)}`;
  return <div className="public-desktop"><main className="public-phone public-settings"><header><Link href="/me" aria-label="返回我的"><ChevronLeft/></Link><div><h1>名片与账号</h1><p>{profile.storeName} · {profile.roleLabel}</p></div></header><section className="settings-identity"><div className="settings-avatar">{profile.avatarUrl?<img src={profile.avatarUrl} alt="名片头像"/>:<UserRound/>}<label title="上传头像"><Camera/><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event)=>void upload("avatar",event.target.files?.[0])}/></label></div><div><strong>{profile.name}</strong><span>登录账号 {profile.username}</span>{profile.avatarUrl&&<button type="button" disabled={busy} onClick={()=>void remove("avatar")}>移除头像</button>}</div></section>{message&&<p className="settings-message" role="status">{message}</p>}<form className="settings-card settings-form" onSubmit={save}><h2><UserRound/> 个人名片</h2><label>姓名<input name="name" defaultValue={profile.name} maxLength={50} required/></label><label>联系电话<input name="phone" defaultValue={profile.phone} pattern="1[0-9]{10}" required/></label><label>真实微信号<input name="wechat" defaultValue={profile.wechat} maxLength={50} required/></label><label>职位<input name="title" defaultValue={profile.title} maxLength={30}/></label><label>简介<textarea name="bio" defaultValue={profile.bio} maxLength={90}/></label><p>登录账号、角色、所属店铺和分享码不可在 APP 修改。</p><button disabled={busy}>保存名片</button></form><section className="settings-card settings-qr"><h2><QrCode/> 微信二维码</h2>{profile.wechatQrUrl?<img src={profile.wechatQrUrl} alt="微信二维码"/>:<div className="settings-qr-empty">尚未上传微信二维码</div>}<div><label className="settings-upload">{profile.wechatQrUrl?"更换二维码":"上传二维码"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event)=>void upload("wechatQr",event.target.files?.[0])}/></label>{profile.wechatQrUrl&&<button type="button" disabled={busy} onClick={()=>void remove("wechatQr")}>删除</button>}</div></section><form className="settings-card settings-form" onSubmit={password}><h2><LockKeyhole/> 修改密码</h2><label>当前密码<input name="currentPassword" type="password" required/></label><label>新密码<input name="newPassword" type="password" minLength={8} maxLength={72} required/></label><button disabled={busy}>修改密码</button></form><Link className="public-back-store" href={sharePath}>查看我的名片</Link><button className="settings-signout" type="button" onClick={()=>void signOut({callbackUrl:"/login"})}><LogOut/> 退出登录</button></main></div>;
}
