export type ImportRow={row:number;name:string;code:string;categoryName:string;mainImageUrl:string;detailImageUrls:string;variantName:string;variantCode:string;priceText:string;stockText:string;unit:string;description:string;sortText:string};
export type ImportProduct={name:string;code:string;categoryName:string;mainImageUrl:string;detailImageUrls:string;unit:string;description:string;sort:number;variants:{name:string;code:string;price:number|null;stock:number|null}[]};
export const V2_HEADERS=["模板版本*","商品名称*","商品编码*","分类名称*","主图URL*","详情图URL","规格名称*","规格编码*","规格参考价","规格参考库存","单位","商品描述","排序"];

const url=/^https?:\/\/\S+$/i;
export function groupImportRows(rows:ImportRow[],existingCodes:Set<string>,categories:Set<string>){
  const errors:{row:number;reason:string}[]=[];const groups=new Map<string,ImportProduct>();const variantCodes=new Set<string>();const invalidCodes=new Set<string>();
  for(const item of rows){let reason="";if(!item.name)reason="商品名称不能为空";else if(!item.code)reason="商品编码不能为空";else if(existingCodes.has(item.code))reason="商品编码在本店已存在";else if(!categories.has(item.categoryName))reason=`分类“${item.categoryName||"空"}”不存在`;else if(!url.test(item.mainImageUrl))reason="主图 URL 格式不正确";else if(item.detailImageUrls&&item.detailImageUrls.split(/\r?\n/).some(x=>!url.test(x.trim())))reason="详情图中存在无效 URL";else if(!item.variantName)reason="规格名称不能为空";else if(!item.variantCode)reason="规格编码不能为空";else if(variantCodes.has(`${item.code}:${item.variantCode}`))reason="同一商品的规格编码重复";else if(item.priceText&&(!Number.isFinite(Number(item.priceText))||Number(item.priceText)<0))reason="规格价格格式不正确";else if(item.stockText&&(!Number.isInteger(Number(item.stockText))||Number(item.stockText)<0))reason="参考库存必须是非负整数";else if(item.sortText&&!Number.isInteger(Number(item.sortText)))reason="排序必须是整数";
    const prior=groups.get(item.code);if(!reason&&prior&&(prior.name!==item.name||prior.categoryName!==item.categoryName||prior.mainImageUrl!==item.mainImageUrl))reason="同一商品编码的基础字段必须一致";
    if(reason){errors.push({row:item.row,reason});if(item.code)invalidCodes.add(item.code);continue}variantCodes.add(`${item.code}:${item.variantCode}`);if(prior)prior.variants.push({name:item.variantName,code:item.variantCode,price:item.priceText?Number(item.priceText):null,stock:item.stockText?Number(item.stockText):null});else groups.set(item.code,{name:item.name,code:item.code,categoryName:item.categoryName,mainImageUrl:item.mainImageUrl,detailImageUrls:item.detailImageUrls,unit:item.unit||"件",description:item.description,sort:item.sortText?Number(item.sortText):0,variants:[{name:item.variantName,code:item.variantCode,price:item.priceText?Number(item.priceText):null,stock:item.stockText?Number(item.stockText):null}]});
  }
  return {products:[...groups.values()].filter(item=>!invalidCodes.has(item.code)),errors};
}
