import { Role } from "@prisma/client";
import { requireActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { FormError, PageHeader } from "@/components/page-header";
import { configureStore, createEnterprise, createStoreAdmin, toggleManagedUser } from "../phase-one-actions";

export default async function OrganizationsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireActor([Role.PLATFORM_ADMIN]); const query = await searchParams;
  const [enterprises, stores, users] = await Promise.all([db.enterprise.findMany({ include: { users: true, series: true }, orderBy: { createdAt: "desc" } }), db.store.findMany({ include: { _count: { select: { users: true } } }, orderBy: { createdAt: "desc" } }),db.user.findMany({where:{role:{in:[Role.ENTERPRISE_ADMIN,Role.STORE_ADMIN,Role.EMPLOYEE]}},include:{store:true,enterprise:true},orderBy:{createdAt:"desc"}})]);
  return <><PageHeader title="组织、账号与功能配额" description="企业与店铺为独立主体；企业默认无法读取店铺客户和订单" /><FormError message={query.error} />
    <details className="panel mb-6"><summary className="cursor-pointer px-5 py-4 font-bold">创建企业及管理员</summary><form action={createEnterprise} className="form-grid border-t p-5"><label className="label">企业名称<input className="field" name="name" required /></label><label className="label">企业编码<input className="field" name="code" required placeholder="factory-a" /></label><label className="label">管理员姓名<input className="field" name="managerName" required /></label><label className="label">登录账号<input className="field" name="username" required /></label><label className="label">初始密码<input className="field" name="password" type="password" minLength={8} required /></label><div className="self-end"><button className="btn btn-primary">创建企业</button></div></form></details>
    <section className="panel table-wrap mb-6"><table><thead><tr><th>企业</th><th>编码</th><th>管理员</th><th>产品系列</th><th>状态</th></tr></thead><tbody>{enterprises.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.code}</td><td>{item.users.map((user) => user.name).join("、")}</td><td>{item.series.length}</td><td>{item.isActive ? "启用" : "停用"}</td></tr>)}</tbody></table></section>
    <section className="panel table-wrap"><table><thead><tr><th>店铺</th><th>账号数</th><th>配额与功能</th><th>新增管理员</th></tr></thead><tbody>{stores.map((store) => <tr key={store.id}><td><strong>{store.name}</strong><div className="muted text-xs">{store.slug}</div></td><td>{store._count.users}</td><td><form action={configureStore} className="flex flex-wrap items-center gap-3"><input type="hidden" name="id" value={store.id} /><label className="text-xs">管理员上限<input className="field mt-1 w-24" name="adminLimit" type="number" defaultValue={store.adminLimit} /></label><label className="text-xs">员工上限<input className="field mt-1 w-24" name="employeeLimit" type="number" defaultValue={store.employeeLimit} /></label>{[["pageEnabled","装修"],["authorizationEnabled","授权"],["customerEnabled","客户"],["analyticsEnabled","分析"]].map(([name,label]) => <label key={name} className="flex gap-1 text-xs"><input type="checkbox" name={name} defaultChecked={store[name as keyof typeof store] === true} />{label}</label>)}<button className="btn min-h-8 px-3 text-xs">保存</button></form></td><td><details><summary className="btn min-h-8 list-none text-xs">新增</summary><form action={createStoreAdmin} className="mt-2 grid min-w-48 gap-2"><input type="hidden" name="storeId" value={store.id}/><input className="field" name="name" placeholder="姓名" required/><input className="field" name="username" placeholder="账号" required/><input className="field" name="password" type="password" placeholder="初始密码" required/><button className="btn btn-primary">创建</button></form></details></td></tr>)}</tbody></table></section>
    <section className="panel table-wrap mt-6"><table><thead><tr><th>账号</th><th>角色</th><th>所属</th><th>状态</th><th>操作</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{user.name}</strong><div className="muted text-xs">{user.username}</div></td><td>{user.role}</td><td>{user.enterprise?.name??user.store?.name??"-"}</td><td>{user.isActive?"启用":"停用"}</td><td><form action={toggleManagedUser}><input type="hidden" name="id" value={user.id}/><button className="btn min-h-8 text-xs">{user.isActive?"停用":"启用"}</button></form></td></tr>)}</tbody></table></section>
  </>;
}
