import ExcelJS from "exceljs";
import { ProductSource, Role } from "@prisma/client";
import { getActiveActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { groupImportRows, ImportRow, V2_HEADERS } from "@/lib/product-import";

const LEGACY=["商品名称*","商品编码*","分类名称*","主图URL*","详情图URL","规格/型号*","参考价格","单位","商品描述","排序"];
const cell=(row:ExcelJS.Row,index:number)=>String(row.getCell(index+1).text??"").trim();
export async function POST(request:Request){const actor=await getActiveActor();if(!actor||actor.role!==Role.STORE_ADMIN||!actor.storeId)return Response.json({error:"无权导入商品"},{status:401});const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||!file.name.toLowerCase().endsWith(".xlsx"))return Response.json({error:"请选择 .xlsx 文件"},{status:400});if(file.size>5*1024*1024)return Response.json({error:"文件不能超过 5MB"},{status:400});
  const workbook=new ExcelJS.Workbook();try{await workbook.xlsx.load(await file.arrayBuffer())}catch{return Response.json({error:"Excel 文件无法读取"},{status:400})}const sheet=workbook.worksheets[0];if(!sheet)return Response.json({error:"Excel 中没有工作表"},{status:400});const first=cell(sheet.getRow(1),0);const v2=first===V2_HEADERS[0];const expected=v2?V2_HEADERS:LEGACY;if(expected.some((header,index)=>cell(sheet.getRow(1),index)!==header))return Response.json({error:"表头不受支持，请使用 V2 模板或原 MVP 模板"},{status:400});
  const rows:ImportRow[]=[];for(let n=2;n<=sheet.rowCount;n++){const row=sheet.getRow(n);if(!row.hasValues)continue;if(v2)rows.push({row:n,name:cell(row,1),code:cell(row,2),categoryName:cell(row,3),mainImageUrl:cell(row,4),detailImageUrls:cell(row,5),variantName:cell(row,6),variantCode:cell(row,7),priceText:cell(row,8),stockText:cell(row,9),unit:cell(row,10),description:cell(row,11),sortText:cell(row,12)});else rows.push({row:n,name:cell(row,0),code:cell(row,1),categoryName:cell(row,2),mainImageUrl:cell(row,3),detailImageUrls:cell(row,4),variantName:cell(row,5),variantCode:`${cell(row,1)}-DEFAULT`,priceText:cell(row,6),stockText:"",unit:cell(row,7),description:cell(row,8),sortText:cell(row,9)})}
  const [categories,existing]=await Promise.all([db.category.findMany({where:{storeId:actor.storeId}}),db.product.findMany({where:{storeId:actor.storeId},select:{code:true}})]);const result=groupImportRows(rows,new Set(existing.map(x=>x.code)),new Set(categories.map(x=>x.name)));const categoryMap=new Map(categories.map(x=>[x.name,x.id]));let success=0;
  for(const product of result.products){try{const firstVariant=product.variants[0];await db.product.create({data:{storeId:actor.storeId,categoryId:categoryMap.get(product.categoryName)!,source:ProductSource.EXCEL,name:product.name,code:product.code,mainImageUrl:product.mainImageUrl,detailImageUrls:product.detailImageUrls,specification:firstVariant.name,price:firstVariant.price,referenceStock:firstVariant.stock,unit:product.unit,description:product.description,sort:product.sort,isPublished:false,variants:{create:product.variants.map((variant,sort)=>({name:variant.name,code:variant.code,price:variant.price,referenceStock:variant.stock,sort}))}}});success++}catch{result.errors.push({row:rows.find(x=>x.code===product.code)?.row??0,reason:"保存失败，商品或规格编码可能重复"})}}
  return Response.json({success,failed:result.errors.length,errors:result.errors});
}
