import ExcelJS from "exceljs";
import { OrderStatus, Role } from "@prisma/client";
import { getActiveActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { orderScope } from "@/lib/scopes";

export async function GET(request: Request) {
  const actor=await getActiveActor();if(!actor||(actor.role!==Role.STORE_ADMIN&&actor.role!==Role.EMPLOYEE)||!actor.storeId)return new Response("Unauthorized",{status:401});
  const params=new URL(request.url).searchParams;const rawStatus=params.get("status");const status=Object.values(OrderStatus).includes(rawStatus as OrderStatus)?rawStatus as OrderStatus:undefined;const ids=params.get("ids")?.split(",").filter(Boolean);const q=params.get("q")??"";const product=params.get("product")??"";const employee=params.get("employee");const responsible=params.get("responsible");const from=params.get("from");const to=params.get("to");
  const filters=[orderScope(actor),...(ids?.length?[{id:{in:ids}}]:[]),...(status?[{status}]:[]),...(employee&&actor.role===Role.STORE_ADMIN?[{sourceEmployeeId:employee}]:[]),...(responsible&&actor.role===Role.STORE_ADMIN?[{responsibleEmployeeId:responsible}]:[]),...(product?[{items:{some:{productName:{contains:product}}}}]:[]),...(from?[{createdAt:{gte:new Date(`${from}T00:00:00`)}}]:[]),...(to?[{createdAt:{lte:new Date(`${to}T23:59:59`)}}]:[]),...(q?[{OR:[{orderNo:{contains:q}},{customerName:{contains:q}},{customerPhone:{contains:q}}]}]:[])];
  const orders=await db.order.findMany({where:{AND:filters},include:{sourceEmployee:true,responsibleEmployee:true,items:true},orderBy:{createdAt:"desc"}});
  const workbook=new ExcelJS.Workbook();const sheet=workbook.addWorksheet("订单");sheet.columns=[{header:"订单编号",key:"orderNo",width:24},{header:"客户姓名",key:"customerName",width:14},{header:"手机号",key:"phone",width:16},{header:"来源员工",key:"source",width:14},{header:"负责人",key:"responsible",width:14},{header:"商品快照",key:"items",width:64},{header:"状态",key:"status",width:12},{header:"地址",key:"address",width:28},{header:"备注",key:"remark",width:28},{header:"提交时间",key:"createdAt",width:22}];
  const labels={PENDING:"待跟进",FOLLOWING:"跟进中",WON:"已成交",LOST:"未成交"};for(const order of orders)sheet.addRow({orderNo:order.orderNo,customerName:order.customerName,phone:order.customerPhone,source:order.sourceEmployee?.name??"店铺默认",responsible:order.responsibleEmployee?.name??"未分配",items:order.items.map(item=>`${item.productName}/${item.specification}${item.variantCode?`(${item.variantCode})`:""} × ${item.quantity}${item.unit}${item.remark?` [${item.remark}]`:""}`).join("；"),status:labels[order.status],address:order.customerAddress,remark:order.customerRemark,createdAt:order.createdAt.toLocaleString("zh-CN")});
  sheet.getRow(1).font={bold:true,color:{argb:"FFFFFFFF"}};sheet.getRow(1).fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF176B45"}};sheet.views=[{state:"frozen",ySplit:1}];const buffer=await workbook.xlsx.writeBuffer();return new Response(buffer as ArrayBuffer,{headers:{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename=orders-${new Date().toISOString().slice(0,10)}.xlsx`}});
}
