"use client";

import { signIn } from "next-auth/react";
import { useState } from "react";

export function CustomerAccess({ storeSlug, refCode, initialMode, returnTo }: { storeSlug:string; refCode:string; initialMode:string; returnTo:string }) {
  const [mode,setMode]=useState(initialMode); const [message,setMessage]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");const data=new FormData(event.currentTarget);
    if(mode==="login"){const result=await signIn("credentials",{username:data.get("phone"),password:data.get("password"),redirect:false});if(result?.error){setMessage("账号未激活，或手机号/密码不正确");return;}if(storeSlug&&refCode){await fetch("/api/customer/attribution",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeSlug,ref:refCode,sessionId:sessionStorage.getItem("yc-session")||undefined})});}window.location.href=returnTo;return;}
    const endpoint=mode==="forgot"?"/api/customer/forgot":"/api/customer/register";const body=mode==="forgot"?{storeSlug,phone:data.get("phone"),newPassword:data.get("password")}:{storeSlug,ref:refCode||null,name:data.get("name"),phone:data.get("phone"),password:data.get("password")};const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(result.error??`${result.message}${result.resetCode?`，申请码：${result.resetCode}`:""}`);
  }
  return <><div className="auth-tabs" role="tablist" aria-label="客户账号操作">{[["login","登录"],["register","注册"],["forgot","忘记密码"]].map(([key,label])=><button key={key} type="button" role="tab" aria-selected={mode===key} onClick={()=>{setMode(key);setMessage("");}}>{label}</button>)}</div><form onSubmit={submit} className="auth-form">{mode==="register"&&<label className="label">姓名<input className="field" name="name" autoComplete="name" required/></label>}<label className="label">手机号<input className="field" name="phone" inputMode="numeric" autoComplete="tel" pattern="1[0-9]{10}" required/></label><label className="label">{mode==="forgot"?"申请启用的新密码":"密码"}<input className="field" name="password" type="password" autoComplete={mode==="login"?"current-password":"new-password"} minLength={8} placeholder="至少 8 位" required/></label>{mode!=="login"&&!storeSlug&&<p className="auth-feedback auth-feedback-error" role="alert">请从具体店铺页面进入注册或找回密码。</p>}<button className="btn btn-primary" disabled={mode!=="login"&&!storeSlug}>{mode==="login"?"登录":"提交人工审核"}</button>{message&&<p className="auth-feedback" role="status">{message}</p>}</form></>;
}
