import Link from "next/link";
import { OrderStatus, Role } from "@prisma/client";
import { Download, FileSpreadsheet, MessageSquare } from "lucide-react";
import { notFound } from "next/navigation";
import { requireActor } from "@/lib/authz";
import { db } from "@/lib/db";
import { formatDate, formatPrice, statusLabel } from "@/lib/format";
import { buildSalesDocument, formatSalesMoney } from "@/lib/order-sales-document";
import { orderScope } from "@/lib/scopes";
import { addOrderNote, saveOrderSalesInfo, updateOrderStatus } from "../../actions";
import { assignOrder } from "../../phase-one-actions";

export default async function OrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}) {
  const actor=await requireActor([Role.STORE_ADMIN,Role.EMPLOYEE]);const {id}=await params;const query=await searchParams;
  const order=await db.order.findFirst({where:{id,...orderScope(actor)},include:{store:true,sourceEmployee:true,responsibleEmployee:true,items:true,notes:{include:{author:true},orderBy:{createdAt:"desc"}},changes:{include:{actor:true},orderBy:{createdAt:"desc"}},lead:true}});if(!order)notFound();
  const employees=actor.role===Role.STORE_ADMIN?await db.user.findMany({where:{storeId:actor.storeId,role:Role.EMPLOYEE,isActive:true},orderBy:{name:"asc"}}):[];
  const sales=buildSalesDocument(order);
  const exportActions=sales.ready?<div className="actions"><a className="btn" href={`/api/orders/${order.id}/image`}><Download size={16}/>导出图片</a><a className="btn" href={`/api/orders/${order.id}/excel`}><FileSpreadsheet size={16}/>导出 Excel</a></div>:<span className="muted text-sm">{order.status===OrderStatus.WON?"请先补齐成交单价":"订单成交后可导出正式销售单"}</span>;
  return <><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link className="muted text-sm" href="/admin/orders">← 返回订单列表</Link><h1 className="page-title mt-3">订单详情</h1><p className="muted mt-2 text-sm">{order.orderNo} · {formatDate(order.createdAt)}</p></div>{exportActions}</div>{query.error&&<div className="mb-5 rounded bg-red-50 p-3 text-red-700">{query.error}</div>}
    <div className="grid gap-5 xl:grid-cols-[1.35fr_1fr]"><section className="grid gap-5"><div className="panel p-5"><div className="mb-4 flex justify-between"><h2 className="font-bold">不可变商品快照</h2><span className="badge">{statusLabel[order.status]}</span></div>{order.items.map(item=><div key={item.id} className="flex items-center gap-3 border-b py-3"><img src={item.imageUrl} alt="" className="size-16 rounded object-cover"/><div className="flex-1"><strong>{item.productName}</strong><p className="muted text-xs">{item.productCode} · {item.specification}{item.variantCode?` · ${item.variantCode}`:""}</p></div><div className="text-right text-sm">{item.quantity} {item.unit}<div className="muted">参考价：{formatPrice(item.price)}</div></div></div>)}</div>
      <div className="panel p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="font-bold">销售单信息</h2><span className="muted text-xs">销售日期：{order.soldAt?formatDate(order.soldAt):"成交时自动记录"}</span></div>{actor.role===Role.STORE_ADMIN?<form action={saveOrderSalesInfo} className="grid gap-4"><input type="hidden" name="id" value={id}/>{order.items.map(item=><div key={item.id} className="rounded border p-4"><div className="mb-3 flex items-center gap-3"><img src={item.imageUrl} alt="" className="size-12 rounded object-cover"/><div><strong className="text-sm">{item.productName}</strong><p className="muted text-xs">{item.specification} · {item.quantity} {item.unit}</p></div></div><div className="grid gap-3 md:grid-cols-3"><label className="label">成交单价<input className="field" name={`salePrice:${item.id}`} inputMode="decimal" required={order.status===OrderStatus.WON} defaultValue={item.salePrice?.toString()??""} placeholder="待补充"/></label><label className="label">颜色<input className="field" name={`color:${item.id}`} maxLength={50} defaultValue={item.color}/></label><label className="label">商品备注<input className="field" name={`remark:${item.id}`} maxLength={200} defaultValue={item.remark}/></label></div></div>)}<div className="grid gap-3 md:grid-cols-2"><label className="label">运费<input className="field" name="shippingFee" inputMode="decimal" required defaultValue={order.shippingFee.toString()}/></label><label className="label">安装费<input className="field" name="installationFee" inputMode="decimal" required defaultValue={order.installationFee.toString()}/></label></div><div className="flex flex-wrap items-center justify-between gap-3 rounded bg-[#f5f7f5] p-3 text-sm"><span>合计数量：<strong>{sales.totalQuantity} 件</strong></span><span>商品金额：<strong>{formatSalesMoney(sales.productAmountCents)}</strong></span><span>应付总额：<strong>{formatSalesMoney(sales.payableAmountCents)}</strong></span></div><button className="btn btn-primary justify-self-start">保存销售单信息</button></form>:<div className="grid gap-3 text-sm"><div className="grid gap-2">{sales.items.map(item=><div className="flex justify-between rounded bg-[#f5f7f5] p-3" key={item.id}><span>{item.productName}{item.color?` · ${item.color}`:""}</span><strong>{formatSalesMoney(item.salePriceCents)} × {item.quantity}</strong></div>)}</div><div className="flex flex-wrap justify-between gap-3 border-t pt-3"><span>运费：{formatSalesMoney(sales.shippingFeeCents)}</span><span>安装费：{formatSalesMoney(sales.installationFeeCents)}</span><strong>应付总额：{formatSalesMoney(sales.payableAmountCents)}</strong></div></div>}</div>
      <div className="panel p-5"><h2 className="mb-4 flex items-center gap-2 font-bold"><MessageSquare size={17}/>跟进备注</h2>{order.notes.map(note=><div key={note.id} className="mb-2 rounded bg-[#f5f7f5] p-3"><p className="text-sm">{note.content}</p><p className="muted mt-2 text-xs">{note.author.name} · {formatDate(note.createdAt)}</p></div>)}<form action={addOrderNote} className="mt-4 flex gap-2"><input type="hidden" name="id" value={id}/><input className="field" name="content" required/><button className="btn btn-primary">添加</button></form></div>
      <div className="panel p-5"><h2 className="font-bold">变更历史</h2><div className="mt-3 grid gap-2">{order.changes.map(change=><p className="text-sm" key={change.id}>{formatDate(change.createdAt)} · {change.actor.name} · {change.field}: {change.beforeValue??"空"} → {change.afterValue??"空"}</p>)}{!order.changes.length&&<p className="muted text-sm">暂无变更</p>}</div></div></section>
      <aside className="grid content-start gap-5"><section className="panel p-5"><h2 className="mb-4 font-bold">客户信息</h2><dl className="grid gap-3 text-sm"><div className="flex justify-between"><dt className="muted">姓名</dt><dd>{order.customerName}</dd></div><div className="flex justify-between"><dt className="muted">手机号</dt><dd>{order.customerPhone}</dd></div><div className="flex justify-between"><dt className="muted">来源员工</dt><dd>{order.sourceEmployee?.name??"店铺默认"}</dd></div><div className="flex justify-between"><dt className="muted">负责人</dt><dd>{order.responsibleEmployee?.name??"未分配"}</dd></div></dl></section>{actor.role===Role.STORE_ADMIN&&<><section className="panel p-5"><h2 className="mb-3 font-bold">分配负责人</h2><form action={assignOrder} className="grid gap-3"><input type="hidden" name="id" value={id}/><select className="field" name="employeeId" defaultValue={order.responsibleEmployeeId??""}><option value="">未分配</option>{employees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn">保存负责人</button></form></section><section className="panel p-5"><h2 className="mb-3 font-bold">处理状态</h2><form action={updateOrderStatus} className="grid gap-3"><input type="hidden" name="id" value={id}/><select className="field" name="status" defaultValue={order.status}>{Object.values(OrderStatus).map(x=><option key={x} value={x}>{statusLabel[x]}</option>)}</select><button className="btn btn-primary">保存状态</button></form></section></>}</aside></div>
  </>;
}
